Added ModelExporter
PrismarineJS/minecraft-data-generator pull request #24
Opened 2024-07-20 10:13 UTC by Nelonn

2024-07-20 10:41 UTC, AlexProgrammerDE commented
Hi, I see you just added a separate git repositiry inside of this repository. Please PR new files into the existing repository instead of making a brand new repository and new mod.

2024-07-20 10:43 UTC, AlexProgrammerDE commented
This code also only works with 1.21. You need to add a file for every version 1.7-1.21

2024-07-20 11:15 UTC, extremeheat commented
Multi version implementations would be nice if you have the time to write it but it's not a requirement as it's not required by anything in PrismarineJS at the moment.

2024-07-20 12:25 UTC, Nelonn commented
> Hi, I see you just added a separate git repositiry inside of this repository. Please PR new files into the existing repository instead of making a brand new repository and new mod.

I'm on macOS and cannot compile 1.12.2 version, so i added separate project that i can build.

```
A problem occurred configuring project ':1.12.2'.
> Failed to notify project evaluation listener.
   > Could not resolve all files for configuration ':1.12.2:minecraftLibraries'.
      > Could not find java-objc-bridge-1.0.0-natives-osx.jar (ca.weblite:java-objc-bridge:1.0.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar
   > Could not resolve all files for configuration ':1.12.2:minecraftLibraries'.
      > Could not find java-objc-bridge-1.0.0-natives-osx.jar (ca.weblite:java-objc-bridge:1.0.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

2024-07-20 12:25 UTC, Nelonn commented
> Multi version implementations would be nice if you have the time to write it but it's not a requirement as it's not required by anything in PrismarineJS at the moment.

Entities don't differ much from version to version and I don't have time to implement this on legacy versions.

2024-07-21 06:57 UTC, AlexProgrammerDE commented
> I'm on macOS and cannot compile 1.12.2 version, so i added separate project that i can build.

This commit will fix it: https://github.com/PrismarineJS/minecraft-data-generator-server/pull/22/commits/5757961d96578f1b94b26d5d26083901cc013da7

> Also I'm using mojang mappings because we shouldn't be dependent of one technology like fabric (I'm talking about yarn mappings)

The team uses yarn because it is consistent from 1.7.-1.21. Being despondent on fabric is good here since it helps maintaining the project.

2024-07-21 06:58 UTC, AlexProgrammerDE commented
> Entities don't differ much from version to version and I don't have time to implement this on legacy versions.

There are enough differences to warrant a implementation per version. But only for 1.21 should be sufficient as extremeheat said.

2024-07-21 06:59 UTC, AlexProgrammerDE commented
Please add the code to the 1.21 module instead of adding a brand new submodule.

2024-07-21 08:22 UTC, Nelonn commented
> > I'm on macOS and cannot compile 1.12.2 version, so i added separate project that i can build.
> 
> This commit will fix it: [5757961](https://github.com/PrismarineJS/minecraft-data-generator-server/commit/5757961d96578f1b94b26d5d26083901cc013da7)
> 
> > Also I'm using mojang mappings because we shouldn't be dependent of one technology like fabric (I'm talking about yarn mappings)
> 
> The team uses yarn because it is consistent from 1.7.-1.21. Being despondent on fabric is good here since it helps maintaining the project.

Merge your PR then I can work on this PR

2024-07-22 15:43 UTC, Nelonn commented
Another issue on macOS after resetting entire gradle cache:

```
A problem occurred configuring project ':1.7'.
> Failed to notify project evaluation listener.
   > Could not resolve all files for configuration ':1.7:minecraftLibraries'.
      > Could not resolve org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20131017.
        Required by:
            project :1.7
         > Could not resolve org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20131017.
            > Could not parse POM https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.1-nightly-20131017/lwjgl-2.9.1-nightly-20131017.pom
               > Could not find org.lwjgl.lwjgl:parent:2.9.1-SNAPSHOT.
```

2024-10-27 09:57 UTC, rom1504 commented
Is this still useful? If yes then please finish it

2024-10-27 10:10 UTC, AlexProgrammerDE requested changes

2024-10-27 10:10 UTC, AlexProgrammerDE commented on 1.20.5/build.gradle
> -    version "1.20.5"
Do not change the 1.20.5 module to 1.21. It needs to stay 1.20.5.

2024-10-27 20:05 UTC, rom1504 commented
Open another PR if you want this finished

2024-10-27 20:05 UTC, closed without merging